apiVersion: autoscaling/v2
kind: HorizontalPodAutoScaler
metadata:
  name: php-apache
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Recource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
    scaleDown:
      stablizationWindowSeconds: 300
      policies:
      - type: Precent
        vale: 10
        periodSeconds: 60
    scaleUp:
      stablizationWindowSeconds: 0
      policies:
      - type: percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: max
